version: '3'
services:
  elasticsearch-master:
    container_name: elasticsearch-master
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    environment:
      - node.name=node-master
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=node-master
      - discovery.seed_hosts=es-node1,es-node2
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - 9200:9200
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./docker-data/esdata-master:/usr/share/elasticsearch/data
    user: "1000:1000"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1.5GB'
        reservations:
          cpus: '1.0'
          memory: '1GB'

  es-node1:
    container_name: es-node1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    environment:
      - node.name=node-1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-master,es-node2
      - cluster.initial_master_nodes=node-master
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./docker-data/esdata-node1:/usr/share/elasticsearch/data
    user: "1000:1000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1GB'
        reservations:
          cpus: '1.0'
          memory: '600MB'

  es-node2:
    container_name: es-node2
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    environment:
      - node.name=node-2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-master,es-node1
      - cluster.initial_master_nodes=node-master
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./docker-data/esdata-node2:/usr/share/elasticsearch/data
    user: "1000:1000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1GB'
        reservations:
          cpus: '1.0'
          memory: '600MB'

  # kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4
    container_name: kibana
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./docker-data/kibanadata:/usr/share/kibana/data
    user: "1000:1000"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-master:9200
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

volumes:
  esdata-master:
    driver: 'local'
  kibanadata:
    driver: 'local'
  esdata-node1:
    driver: 'local'

networks:
  elastic:
    name: 'elastic'
    driver: 'bridge'
